name: roloxmoney
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dynamic_themes: ^1.1.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  pin_code_fields: ^7.4.0
  flutter_svg: ^1.1.4
  dio: ^5.0.1
  altogic: ^1.0.6
  shared_preferences: ^2.1.1
  supabase_flutter: ^1.10.9
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  flutter_cached_pdfview: ^0.4.2

#  firebase_auth: ^3.6.4
#  firebase_auth:
##  firebase_core: ^1.21.0
#  firebase_core:
##  firebase_remote_config: ^2.0.15
#  firebase_remote_config:
#  firebase_analytics: ^9.3.2
#  firebase_analytics:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/png/bottom_navigation/

  fonts:
    - family: Poppins-Light
      fonts:
        - asset: fonts/Poppins-Light.ttf
    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Poppins-MediumItalic
      fonts:
        - asset: fonts/Poppins-MediumItalic.ttf
    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf